name: ci

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: cross-env

      - name: Build cross-env
        run: |
          cd ./cross-env
          make linux

      - uses: actions/upload-artifact@v2
        with:
          name: linux
          path: |
            ./bin/cross-env/cross-env_linux_amd64
            # ./bin/cross-env/cross-env_linux_386
          if-no-files-found: error

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build V
        run: |
          .\make.bat -msvc

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: cross-env

      - name: Build cross-env
        run: |
          $env:path += ";$(get-location)"
          cd ./cross-env
          make windows

      - uses: actions/upload-artifact@v2
        with:
          name: windows
          path: |
            .\\bin\\cross-env/cross-env_windows_amd64.exe
            # .\\bin\\cross-env/cross-env_windows_386.exe
          if-no-files-found: error

  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v

      - name: Build V
        run: |
          make
          sudo ./v symlink

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: cross-env

      - name: Build cross-env
        run: |
          cd ./cross-env
          make macos

      - uses: actions/upload-artifact@v2
        with:
          name: macos
          path: ./bin/cross-env/cross-env_darwin_amd64
          if-no-files-found: error

  release:
    name: Release to Github
    if: startsWith(github.ref, 'refs/tags/') && github.repository == 'axetroy/cross-env'
    needs: [linux, windows, macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: linux

      - uses: actions/download-artifact@v2
        with:
          name: windows

      - uses: actions/download-artifact@v2
        with:
          name: macos

      - name: tar
        run: |
          mv cross-env_linux_amd64 cross-env && chmod +x cross-env && tar czf cross-env_linux_amd64.tar.gz cross-env && rm cross-env
          # mv cross-env_linux_386 cross-env && chmod +x cross-env && tar czf cross-env_linux_386.tar.gz cross-env && rm cross-env
          mv cross-env_darwin_amd64 cross-env && chmod +x cross-env && tar czf cross-env_darwin_amd64.tar.gz cross-env && rm cross-env
          mv cross-env_windows_amd64.exe cross-env.exe && chmod +x cross-env.exe && tar czf cross-env_windows_amd64.tar.gz cross-env.exe && rm cross-env.exe
          # mv cross-env_windows_386.exe cross-env.exe && chmod +x cross-env.exe && tar czf cross-env_windows_386.tar.gz cross-env.exe && rm cross-env.exe
          ls -lh

      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          files: |
            cross-env_linux_amd64.tar.gz
            # cross-env_linux_386.tar.gz
            cross-env_darwin_amd64.tar.gz
            cross-env_windows_amd64.tar.gz
            # cross-env_windows_386.tar.gz
          draft: false
